#' @param api This can be
#'   * an OpenAPI Specification formatted list object
#'   * a function that accepts the OpenAPI Specification autogenerated by `plumber` and returns a OpenAPI Specification formatted list object.
#'   * a path to an OpenAPI Specification
#'
#'  The value returned will not be validated for OAS compatibility.
